### ISSUE TITLE
x-y plane airplane movement

### ISSUE THREAD

**Issue by MMWAVEMJK** [cthompson165/pyAirplane#38]
Hello, i am  interested  your work and i will be happy if you share code for airplane movement in x-y plane that show how airplane turning from top of the airplane.

**Comment by cthompson165** [comment]
This is a 2d simulator so the plane doesn't really have a way to turn (yaw or roll) - only go up and down (pitch). Best place to see that is in https://github.com/cthompson165/pyAirplane/blob/master/examples/sprites/plane_sprite.py. It calls the flight/Airplane class's "apply_pitch_control" method.

**Comment by MMWAVEMJK** [comment]
What I meant was whether this simulation is not done from the top of the plane in 2D, so that the rotation of the plane can be observed ? Can you guide me to write the code related to the rotation of the plane (roll or turn) ?

**Comment by cthompson165** [comment]
Ah. I see what you are saying. You could do it, but I'm not sure it'd be worth it. In 2d looking down you'd only have rudder control that would swing the tail left and right. Without role, which would require 3d, the wings would be aimed almost directly into the turn so you'd actually have less surface area exposed in the direction of travel than you would when changing pitch. So you'd end up kicking the tail out of the left, for example, and then the plane would slide sideways for a while until the surface of the fuselage generated enough lift to change the plane's direction to line up with it's heading. The code for that would be very similar to the sideways view. To implement, I'd recommend:

- Create a new plane object (e.g. YawOnlyAirplane)
- Rename all the elevator controls with rudder controls
- Change the horizontal stabilizer to a vertical stabilizer. Look up the surface area for whatever plane your are modeling.
- Looks like I only have a drag curve on the fuselage so the current simulator doesn't consider it at all when figuring out lift - it just uses wings and horizontal stabilizer.  This would be the tricky part. You'd need to add a lift curve to the fuselage since the wings wouldn't be doing much to turn the plane when it is yawing. Otherwise the plane wouldn't change direction much at all - it would just fly sideways for a while until the lift on the vertical stabilizer straightened it back out in the same direction of travel (think of an arrow with feathers at the back). Not sure what the fuselage lift curve would be. I just took a quick look around on the internet and didn't find anything estimating the lift curve of a rod. Maybe use a flat plate (with the width and length of the fuselage when looking down) as a starting point (https://www1.grc.nasa.gov/beginners-guide-to-aeronautics/foilsimstudent/). 
- Add a new sprite image with the top down version of a plane in examples/images
- Add a new sprite class in examples/sprites. This is going to be the same code as the existing sprite, but with calls to update the rudder rather than the elevator
- Either update the fly_a_747 example or add a new one to use your new sprite and YawOnlyAirplane classes

Good luck! Let me know how it goes if you get it working
